.tool-versions, bootstrap.lock, go.mod, go.sum, pkg/codegen/codegen.go, pkg/codegen/fetcher.go, pkg/configuration/configuration.go, pkg/extensions/apiv1/client.go, pkg/extensions/apiv1/extensions.go, pkg/extensions/apiv1/plugin.go, pkg/extensions/caller.go, pkg/extensions/extensions.go, pkg/extensions/github/github.go, service.yaml
**What this PR does / why we need it**: This PR adds support for basic go extensions to stencil. An extension is made via go-plugin. A basic example of a plugin looks like so:
```go
type TestPlugin struct{}
func (tp *TestPlugin) GetConfig() (*apiv1.Config, error) {
return &apiv1.Config{
Name: "test",
}, nil
}
func (tp *TestPlugin) ExecuteTemplateFunction(t *apiv1.TemplateFunctionExec) (interface{}, error) {
return hello()
}
func (tp *TestPlugin) GetTemplateFunctions() ([]*apiv1.TemplateFunction, error) {
return []*apiv1.TemplateFunction{
{
Name:          "hello",
ArgumentTypes: []interface{}{""},
ReturnType:    "",
},
}, nil
}
func hello() (interface{}, error) {
return "hello from a plugin!", nil
}
func main() {
err := apiv1.NewExtensionImplementation(&TestPlugin{})
if err != nil { …
```
=> feat: add negotiation support for go-extensions

pkg/functions/stencil.go
Adds a new `stencil.Args` function that enables accessing the raw arguments map instead of going through `stencil.Arg`. I don't feel there's any real value to dot notation besides gating the accessor for arguments which I also don't find useful.
Intended use:
```tpl
{{- (stencil.Args).dependencies.required }}
```
**JIRA ID**: [DTSS-0]
=> feat(stencil) expose stencil.Args, stencil.Arg calls w/ no name

go.mod, go.sum, internal/codegen/stencil.go, internal/codegen/stencil_test.go, internal/codegen/tpl_stencil.go, internal/dotnotation/dotnotation.go, internal/dotnotation/dotnotation_test.go, internal/git/git.go, pkg/configuration/configuration.go
This PR introduces the concept of "module hooks" which are cross-module blocks that modules can write to. These enable modules to programmatically insert contents into another module in a predictable way.
There are currently restrictions on the type of data that is allowed to be passed, they must be slices or maps. This helps ensure that multiple modules are able to write to the same hook without the possibility of being overwritten. If the same hook is written more than once, the data is merged together via mergo.
[DTSS-1379]
[DTSS-1379]: https://outreach-io.atlassian.net/browse/DTSS-1379?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(codegen): support templates injecting data cross-modules

internal/codegen/tpl_stencil.go, internal/dotnotation/dotnotation.go, internal/dotnotation/dotnotation_test.go
Yaml returns `map[interface{}]interface{}` for maps, so we need to handle that in `dotnotation`.
[XX-XX]
=> fix(stencil): properly handle yaml map type

cmd/stencil/create.go, cmd/stencil/create_templaterepository.go, cmd/stencil/stencil.go
This PR adds a `create templaterepository` command that enables users to quickly create a template repository
[XX-XX]
=> feat(create): add create and create templaterepository commands

internal/codegen/tpl_stencil.go
Minor optimization to not assume the list type when returning a default value
[XX-XX]
=> fix(tpl/stencil): return []interface{}{} instead of []string for list default

internal/codegen/stencil.go
Keeping templates in the root has been... a big mistake, so, instead, we'll place them in `templates/` and keep the behavior but treating that as a "chroot".
[DTSS-0]
=> fix(stencil): use templates/ as the base directory if present

internal/codegen/values_test.go, internal/git/git.go
I added `-n` because it doesn't require network connectivity and seemed to still work, but apparently it breaks sometimes when a remote has never been queried before, so, we remove it again.
[XX-XX]
=> fix(git): query remote for HEAD branch

.vscode/launch.json, go.mod, internal/cmd/stencil/stencil.go, internal/codegen/file.go, internal/codegen/stencil.go, internal/codegen/template.go, internal/codegen/template_test.go, internal/codegen/tpl.go, internal/codegen/tpl_file.go, internal/codegen/tpl_stencil.go
This PR changes module hooks to only accept slices and to return `[]interface{}` instead of `interface{}`. This brings us better in line with the true value of hooks, which is for multiple items.
Module hooks previously erroneously shared a slice between first pass and second pass. This would result in module hooks working but not persisting their contents because of how the template default file system works. This is now fixed by clearing `Files` between runs, which is the only mutated field of a template struct. This is also more memory efficient. This will be improved upon when we move to a selective rerender system in the future.
Debugging has also been beefed up by adding module hook logs into the `--debug` logs.
[XX-XX]
=> fix: only support []interface{} for hooks, module hooks render properly

cmd/stencil/create_templaterepository.go, go.mod, internal/modules/modules.go, stencil.lock
This PR updates `create templaterepository` to default to pre-releasing them. I also fixed an issue with top level modules being unable to override dependency versions, with a note on a better path forward for the future.
[XX-XX]
=> feat: prerelease templaterepositories by default, support module version override

internal/codegen/functions.go, internal/codegen/functions_test.go, internal/codegen/tpl_stencil.go
**What this PR does**: This PR adds `toJson` and `fromJson` to the templates to support reading/processing JSON files. Also added is `stencil.ReadFile` to read a file from the current directory. This will be used to process a JSON file in go-templates without requiring a go module for it.
=> feat: add to/fromJSON and stencil.ReadFile

go.mod, go.sum, internal/cmd/stencil/stencil.go, internal/modules/module.go, pkg/extensions/extensions.go
**What this PR does**: This PR updates the github client calls to allow no auth, passing a logger where possible. I also changed the handling of local module replacements to support no `file://` prefix (which always felt terse) but also to report errors when the replacement isn't found. This should increase the UX of local replacements.
=> feat: allow unauthenticated github client, better handle local modules

go.mod, go.sum, internal/codegen/stencil.go, internal/modules/module.go, internal/modules/module_test.go, pkg/configuration/configuration.go, pkg/configuration/type.go, pkg/configuration/type_test.go, pkg/extensions/apiv1/apiv1.go, pkg/extensions/extensions.go, pkg/stenciltest/inproc_ext.go, pkg/stenciltest/stenciltest.go
With smartstore and clerk repos, we would love to have stencil support a repo with both templates and plugin (extension) colocated together (otherwise we need stencil-smartstore and stencil-smartstore-ext and it would be really annoying to maintain them separately).
This PR includes:
* [BREAKING] intro new TemplateRepositoryTypes and replace the stencil module type from a plain string to  TemplateRepositoryTypes
* add MarshalYAML/UnmarshalYAML for the new TemplateRepositoryTypes to treat the in/out as plain string.
* [BREAKING] remove TemplateRepositoryTypeStd - leaving it as empty and as an equivalent of "templates" will be terribly confusing people, I added TemplateRepositoryTypeTemplates instead
* unit tests
Also tested in orchestration with bootstrap + stencil-smartstore PR pending …
=> feat: multi-type repo support

pkg/stenciltest/stenciltest.go
This PR allows stenciltest.Run to continue trying rest of the templates and avoid stopping if a single one of them fails. This is useful if test if the 'save' flag is true. This is useful if this test wants to generate a large bulk of snapshot files - in this case input arg will be true and we do not want to test to stop until all snapshots are generated. It is also useful when errors between templates are 'distinct' - devs run the test once and see all the sub-test errors in one shot.
[DTSS-00]
=> fix: make sure stenciltest.Run shows all bad templates or templates with outdated snapshot in one run

internal/codegen/tpl_file.go
Adds a file.RemoveAll directive to remove all files within the given path. This is needed so that stencil modules can delete all files if needed. This was supported by bootstrap and hence this change fixes the breaking feature.
```
{{- file.RemoveAll $path}}
```
[DP-3732]
I created a local `stencil` binary and ran on a test repo to verify the change.
[DP-3732]: https://outreach-io.atlassian.net/browse/DP-3732?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: Add file.RemoveAll directive for templates

internal/codegen/tpl_file.go, internal/codegen/tpl_stencil.go
Custom template function will only raise their error correctly they return two arguments, the second of which being an error. This PR makes sure all our custom function that return an error return two arguments so the second one can raise the correct error.
[DTSS-1817]
New error for missing start block:
```
ERRO[0005] failed to run: run codegen: failed to render template 1 "github.com/getoutreach/stencil-golang/cmd/main_cli.go.tpl": template: github.com/getoutreach/stencil-golang/cmd/main_cli.go.tpl:87:7: executing "github.com/getoutreach/stencil-golang/cmd/main_cli.go.tpl" at <file.Create>: error calling Create: invalid EndBlock when not inside of a block, at cmd/polaroid-cli/polaroid-cli.go:17
ERRO[0009] failed to run: failed to run stencil: exit status 1
```
Old error for missing start …
=> fix: bubble up tpl function errors

internal/codegen/blocks.go, internal/codegen/blocks_test.go, internal/codegen/testdata/blocks-test.txt
We added block `circleE2EExtra` in stencil-circleci [some time ago](https://github.com/getoutreach/stencil-circleci/pull/13) but it is not working because the block name includes digit which is not matched as valid block name by stencil. This PR introduces digits in block names.
[DT-2042]
[DT-2042]: https://outreach-io.atlassian.net/browse/DT-2042?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: allow digits in block name

go.mod, go.sum, internal/codegen/tpl_stencil.go, internal/codegen/tpl_stencil_test.go
This PR changes our JSON Schema parsing library to be a more modern library, with support for Draft 2020 (the latest). This also improves the error messages produced by stencil, and pulls it out into it's own function.
`serviceActivities` with incorrect value:
```bash
ERRO[0007] failed to run: run codegen: failed to render template "github.com/getoutreach/stencil-golang/.vscode/extensions.json.tpl": template: github.com/getoutreach/stencil-golang/.vscode/extensio
ns.json.tpl:14:35: executing "github.com/getoutreach/stencil-golang/.vscode/extensions.json.tpl" at <stencil.Arg>: error calling Arg: module "github.com/getoutreach/stencil-golang" argument "service
Activities" validation failed: value must be one of "http", "grpc", "temporal", "kafka"
```
[XX-XX]
=> feat: change jsonschema library, better error messages 2020 draft

.prettierignore, docs/content/en/commands/stencil.md, docs/content/en/commands/stencil_create.md, docs/content/en/commands/stencil_create_module.md, docs/content/en/commands/stencil_describe.md, docs/content/en/functions/file.Block.md, docs/content/en/functions/file.Create.md, docs/content/en/functions/file.Delete.md, docs/content/en/functions/file.Path.md, docs/content/en/functions/file.SetContents.md, docs/content/en/functions/file.SetPath.md, docs/content/en/functions/file.Skip.md, docs/content/en/functions/file.Static.md, docs/content/en/functions/stencil.AddToModuleHook.md, docs/content/en/functions/stencil.ApplyTemplate.md, docs/content/en/functions/stencil.Arg.md, docs/content/en/functions/stencil.Args.md, docs/content/en/functions/stencil.GetModuleHook.md, docs/content/en/functions/stencil.ReadFile.md, docs/content/en/reference/template-module.md, docs/gen/commands/main.go, docs/gen/functions/main.go, internal/codegen/stencil_test.go, internal/codegen/tpl_file.go, internal/codegen/tpl_stencil.go, internal/codegen/tpl_stencil_arg.go, internal/codegen/tpl_stencil_arg_test.go, internal/modules/modulestest/modulestest.go, pkg/configuration/configuration.go, pkg/stenciltest/stenciltest.go
This PR adds a new `from` field to the argument module spec. `from` alias the current argument name, based on the key in the `arguments` map, to another module's argument spec.
**Example**:
```yaml
name: test-0
arguments:
hello:
from: test-1
name: test-1
arguments:
hello:
schema:
type: string
```
`test-0.hello` would inherti all the properties of the `test-1.hello` argument.
There's a few special rules here:
* When `from` is set, no other keys apply. e.g. if you have `from` and `schema`, `schema` would be ignored in favor of the `schema` in the module referenced. There is no sort of merging.
* An argument using `from` must declare it as a dependency in the `modules` list for `from` to work, otherwise a runtime-error will occur
[XX-XX]
=> feat(arguments): support from to alias to another module's argument

internal/codegen/stencil.go, internal/codegen/stencil_test.go, pkg/stencil/stencil.go, pkg/stencil/stencil_test.go, pkg/stencil/testdata/stencil.lock
This PR removes the `generated` field from the `stencil.lock` file, this doesn't really serve a purpose but it sure does like to cause merge conflicts.
Also removed is `skipped` and `deleted` files from the lockfile, this caused sorting issues and they didn't really need to be written because they don't get written.
[XX-XX]
=> fix(lockfile): remove generated, dont show deleted/skipped files in lock

docs/content/en/functions/stencil.ReadBlocks.md, internal/codegen/tpl_stencil.go, internal/codegen/tpl_stencil_test.go
This PR adds `stencil.ReadBlocks "path"` to read the blocks out of an arbitrary path. This is useful for moving files from one place to the other, or some other attempt at reading the blocks of another file.
[XX-XX]
=> feat(tpl): add stencil.ReadBlocks to parse blocks from arbitrary files

bootstrap.lock, cmd/stencil/stencil.go, internal/cmd/stencil/stencil.go, internal/modules/module_test.go, internal/modules/modules.go
The version resolver does a great job of persisting constraints across version resolves, but it did not calculate channels properly. This fixes that to calculate channels, and error when more than one channel is requested (since we do not know the logical flow of a channel in terms of promotion)
[DT-2808]
[DT-2808]: https://outreach-io.atlassian.net/browse/DT-2808?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(modules): properly persist channel resolve information

internal/codegen/blocks.go, internal/codegen/blocks_test.go, internal/codegen/testdata/v2blocks-invalid.txt, internal/codegen/testdata/v2blocks-test.txt
This PR adds a new block format (v2) to get around issues with comment fomatters that would break the traditional `///`, among other cases, blocks.
The new block format looks like so:
```go
// <<Stencil::Block(name)>>
fmt.Println("Block stuff does block things")
// <</Stencil::Block>>
```
[DT-0]
=> feat(blocks): use safer block format (v2)

internal/codegen/tpl_stencil.go
This PR adds a `stencil.Exists` template function to check if a file exists in the current directory. The logic behind this function is that when a [go-template function returns an error, the template execution is halted](https://pkg.go.dev/text/template#FuncMap). This makes it painful to use `stencil.ReadFile` when doing custom "static-like" logic. While it'd be more effective to add a `catch` or `stencil.Call` function to handle that error for the user, we have more we'll want to do there in the future for a `ApplyTemplate` revamp to better support template helpers, so I'm not doing that yet.
[DT-2808]
[DT-2808]: https://outreach-io.atlassian.net/browse/DT-2808?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(codegen/stencil): add stencil.Exists tpl function

pkg/extensions/apiv1/apiv1.go
With the move to different yaml/json libraries sometimes we can get `map[interface{}]interface{}` instead of `map[string]interface{}`, we should generally support that anyways, so we register that type now.
[DT-2808]
[DT-2808]: https://outreach-io.atlassian.net/browse/DT-2808?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(extensions): support map[interface{}]interface{}

cmd/stencil/describe.go, cmd/stencil/describe_test.go, internal/cmd/stencil/stencil.go, internal/codegen/file.go, internal/codegen/tpl_file.go
This PR adds `SkipReason` (which is already in the function signature, but not used) in debug logs, and static log debugging. I also fixed #157.
[DT-2902]
[DT-2902]: https://outreach-io.atlassian.net/browse/DT-2902?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: small UX/debugging improvements

internal/cmd/stencil/stencil.go, internal/modules/module_test.go, internal/modules/modules.go, pkg/stenciltest/stenciltest.go, pkg/stenciltest/stenciltest_test.go
This PR adds support for resolving the dependencies of modules in-memory. This adds the notion of `dontResolve` to a `rm` (`ResolvedModule`)  that prevents a module from ever attempting to be resolved again (we re-resolve modules to ensure that additive criterias are considered).
This is used in combination with the new `ModuleResolveOptions` type that is passed to `GetModulesForService` that supports setting `Replacements` to be used to like the current `replacements` option in a `service.yaml`, but for in-memory modules.
[XX-XX]
=> feat(modules): support resolving dependencies of in-memory modules

internal/codegen/stencil_test.go, internal/codegen/tpl_stencil_arg_test.go, internal/codegen/values_test.go, internal/modules/module_test.go, internal/modules/modulestest/modulestest.go, pkg/stenciltest/stenciltest.go, pkg/stenciltest/stenciltest_test.go
Uses the full manifest when running tests. This makes sure all present and future fields get passed through without extra housekeeping. 
[DT-2896]
[DT-2896]: https://outreach-io.atlassian.net/browse/DT-2896?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: use full manifest in tests

internal/cmd/stencil/stencil.go, internal/codegen/stencil_test.go, internal/codegen/tpl_stencil_arg_test.go, internal/codegen/values_test.go, internal/modules/module_test.go, internal/modules/modules.go, internal/modules/modulestest/modulestest.go, pkg/stenciltest/stenciltest.go, pkg/stenciltest/stenciltest_test.go
Support from was a matter of loading dependent modules in tests.
You can see this working in https://github.com/getoutreach/stencil-outreach/pull/59.
[DT-2896]
[DT-2896]: https://outreach-io.atlassian.net/browse/DT-2896?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: support from manifest arugments in tests

internal/codegen/tpl_stencil_arg.go, internal/codegen/tpl_stencil_arg_test.go
This PR introduces better error messages for jsonschema validation. If there is a validation error, it will now look like:
```
ERRO[0007] Encountered a validation error for "arguments.releaseOptions.allowMajorVersions": expected boolean, but got string 
ERRO[0007] failed to run: run codegen: failed to render template "github.com/getoutreach/stencil-base/.releaserc.yaml.tpl": template: github.com/getoutreach/stencil-base/.releaserc.yaml.tpl:19:21: executing "github.com/getoutreach/stencil-base/.releaserc.yaml.tpl" at <stencil.Arg>: error calling Arg: module "github.com/getoutreach/stencil-base" validation failed 
```
It also provides the full path even for complex schemas (like smartstore) that include nested field validations.
[DT-3149]
[DT-3149]: …
=> fix: better jsonschema validation errors

internal/modules/module.go, pkg/extensions/extensions.go, pkg/extensions/extensions_test.go
Uses the commit for caching instead of the tag. This helps ensure we grab the same version even when we change the tag. Most commonly this happens with `unstable` as it is a dynamic tag.
[DT-3191]
[DT-3191]: https://outreach-io.atlassian.net/browse/DT-3191?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: cache stencil modules using commit

internal/codegen/values.go
Currently, if the box config fails to load we set a nil value. This causes nil pointer dereferences. Now, we set a value to prevent that from ocurring.
[XX-XX]
=> fix(values): default box config when failed to load

go.mod, internal/codegen/tpl_stencil.go, internal/modules/module_test.go, internal/modules/modules.go
This PR fixes the documented using branches in `version` field for modules. This wasn't working, despite being documented due to the contrainst work done awhile ago. To enable this, when we can't parse a valid constraint out of `version`, we assume we're using a branch. `channel` is essentially a glorified branch system (with support for pre-release versions), so we alias `Version` to `Channel` when this is supplied.
Longer term we should remove channels and only support constraint or branch.
[DT-3366]
[DT-3366]: https://outreach-io.atlassian.net/browse/DT-3366?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(modules): properly resolve branches as versions

go.mod, go.sum, internal/codegen/stencil.go, internal/codegen/tpl_stencil.go, internal/codegen/tpl_stencil_test.go
This PR adds sorting to module hooks by using `hashstructure`, falling back to `fmt.Sprintf("%v")`. This makes re-runs of stencil more reproducible, since module hook insertion order is not guaranteed because file execution order is not.
[DT-3484]
[DT-3484]: https://outreach-io.atlassian.net/browse/DT-3484?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(module-hooks): sort module hook data

internal/codegen/tpl_stencil.go, service.yaml
This PR fixes a panic on a module hook that has no data.
[XX-XX]
=> fix: panic on GetModuleHook that doesnt exist

cmd/stencil/create_module.go, docs/content/en/getting-started/module-quick-start.md
Adds the dependency for stencil-circleci and stencil-base here since both were removed from stencil-template-base.
[DT-3579]
[DT-3579]: https://outreach-io.atlassian.net/browse/DT-3579?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: stencil create module depend on stencil-circleci and stencil-base

.circleci/config.yml, stencil.lock
Promote unstable to rc, created by `dt release promote`
**DO NOT MERGE**
=> chore: Promote unstable to rc

docs/content/en/reference/native-extensions.md
Please read [CONTRIBUTING.md](CONTRIBUTING.md) for additional information on contributing to this repository!
Address the comment for merged PR. (https://github.com/getoutreach/stencil/pull/302#discussion_r1432013066)
[XX-XX]
=> fix(docs): add instructions in how to find binaries path

pkg/stenciltest/stenciltest.go
Makes it easier to regenerate snapshots locally, but also show a diff (and not regenerate them) in CI.
=> feat(stenciltest): add RegenerateSnapshots function

docs/.tool-versions, go.mod, go.sum, internal/gitauth/gitauth.go, internal/modules/module.go, pkg/extensions/extensions.go
Replace the `git-urls` dependency with a [fork](https://github.com/chainguard-dev/git-urls), to fix a Dependabot alert. From the fork's README:
> This repository is a fork of [git-urls](https://github.com/whilp/git-urls). The fork was created to fix an existing vulnerability [GHSA-3f2q-6294-fmq5](https://github.com/advisories/GHSA-3f2q-6294-fmq5) in the upstream repository, which looked unmaintained.
>
> Chainguard plans to keep maintaining this repository under our organization.
=> fix: replace vulnerable, unmaintained dependency with maintained fork

pkg/configuration/configuration.go
Hopefully this will cause `prerelease` to only be emitted if it is `true`.
=> fix(configuration): annotate omitempty on deprecated prerelease attribute

pkg/configuration/configuration.go
This makes it so that `arguments` follows `name` when marshaling to YAML.
=> fix(configuration): move Arguments so marshaling is consistent

README.md
This is for three reasons:
1. Note that a community version exists
2. Make it clear that we don't have the time to handle community requests
3. Allow the community version to use the Homebrew package identifier instead ([ref](https://github.com/orgs/Homebrew/discussions/5587))
=> chore: maintenance mode announcement

.github/workflows/gh-pages.yaml, docs/.tool-versions
The Ubuntu 20.04 runner is being removed ([ref](https://github.blog/changelog/2025-01-15-github-actions-ubuntu-20-runner-image-brownout-dates-and-other-breaking-changes/)).
Also replaces `asdf` in the runner with `mise`.
=> ci(gh-pages): upgrade runner from Ubuntu 20.04 to 24.04, migrate job from asdf to mise

.circleci/config.yml, internal/git/git.go, internal/git/git_test.go, scripts/test-pre-setup.sh
If a user sets their `LC_ALL` to a non-English value, and that language has a translation file for `git`, `git.DefaultBranch` will fail since it's [searching using the English output](https://github.com/getoutreach/stencil/blob/c801ba2cdc1f3a5e92e5010ee4799c709388ba7b/internal/git/git.go#L27).
Instead of setting `LC_ALL=C` when calling `git`, I have elected to convert it to use `go-git`, to avoid this whole mess entirely.
The test was written to fail with the current behavior, and passes with the changes (and also passes if we set `LC_ALL=C`).
[DT-4814]
[DT-4814]: https://outreach-io.atlassian.net/browse/DT-4814?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: avoid default branch errors when using non-English for LC_ALL
