getoutreach/stencil

- docs/creating-a-template-repository.md
Adds some docs!
**JIRA ID**: [DTSS-589]
[DTSS-589]: https://outreach-io.atlassian.net/browse/DTSS-589?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs: add template repository intro

- pkg/codegen/fetcher.go
- pkg/configuration/configuration.go
Title says, it does.
**JIRA ID**: [XX-XX]
> feat(fetcher): support branches, note lack of commit support

- docs/creating-a-template-repository.md
- docs/getting-started.md
- docs/reference-docs/blocks.md
- docs/reference-docs/module-hooks.md
- docs/reference-docs/templates.md
- docs/using-stencil.md
- internal/codegen/file.go
This PR adds basic documentation around getting started and reference docs.
[DTSS-1378]
[DTSS-1378]: https://outreach-io.atlassian.net/browse/DTSS-1378?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs: add reference and getting-started docs

- internal/modules/module.go
> chore: fix error message typo

- CONTRIBUTING.md
- docs/creating-a-template-repository.md
- internal/codegen/tpl_stencil.go
- pkg/extensions/apiv1/extensions.go
- pkg/extensions/extensions.go
> fix: use the correct 'its' as necessary

- cmd/stencil/create_templaterepository.go
- pkg/configuration/configuration.go
> feat(create/templaterepository): use template-base, run stencil

- cmd/stencil/stencil.go
We've essentially been relying on the devenv to refresh the box configuration, but that's not really the best behaviour. Now we refresh the box configuration ourself pre-loading it, but only if it already exists. I don't want to make it a requirement to run stencil right now.
[XX-XX]
> fix: refresh box config before load

- go.mod
- internal/codegen/stencil.go
- internal/modules/module.go
- pkg/extensions/extensions.go
> fix: load plugin

- README.md
- docs/_vendor/github.com/gohugoio/gohugoioTheme/layouts/partials/site-nav.html
- docs/config.toml
- docs/config/_default/config.toml
- docs/netlify.toml
This PR adds netlify integration to support preview URLs automatically. Github pages is still being used for the deployment.
[XX-XX]
This PR depends on #90. The only changes in this PR are in this commit: https://github.com/getoutreach/stencil/pull/91/commits/9ea2b015f430a71e5767483e44027b893a48a79e
> docs: netlify

- docs/_vendor/github.com/gohugoio/gohugoioTheme/layouts/partials/home-page-sections/open-source-involvement.html
> docs(theme): fix typo

- go.mod
- go.sum
**What this PR does**: This PR updates gobox to ensure we have access to the latest box config fields
> fix: update gobox

- cmd/stencil/create_module.go
* add arguments to get releasing working for native extensions
[XX-XX]
> fix: stencil create

- internal/codegen/template_test.go
- internal/codegen/testdata/generated-block/fake.txt
- internal/codegen/testdata/generated-block/template.txt.tpl
This PR adds a test that validates that generated blocks function as expected.
[XX-XX]
> tests: add generated block test

- internal/modules/module.go
This PR fixes the version resolver for modules for pre-releases to only be `-rc`, before it would be the latest release. This will be adjusted in the version resolver rewrite coming soon.
[XX-XX]
> fix(resolver): only consider -rc releases for pre-releases

- pkg/extensions/apiv1/apiv1.go
Promote unstable to rc, created by `dt release promote`
**DO NOT MERGE**
> Promote unstable to rc

- cmd/stencil/stencil.go
Adds a honeycomb dataset so we can correctly report traces and avoid errors like:
```
2022/09/26 11:00:29 rpc error: code = Unauthenticated desc = missing 'x-honeycomb-dataset' header
```
[XX-XX]
> fix: pass honeycomb dataset

- .circleci/config.yml
- .github/dependabot.yml
- .vscode/launch.json
- bootstrap.lock
- internal/cmd/stencil/stencil.go
- internal/cmd/stencil/stencil_test.go
- internal/modules/module_test.go
- opslevel.yml
- service.yaml
- stencil.lock
Promote unstable to rc, created by `dt release promote`
**DO NOT MERGE**
> chore: Promote unstable to rc

- .circleci/config.yml
- .github/dependabot.yml
- .tool-versions
- .vscode/launch.json
- bootstrap.lock
- go.mod
- go.sum
- internal/cmd/stencil/stencil.go
- internal/cmd/stencil/stencil_test.go
- internal/modules/module_test.go
- opslevel.yml
- pkg/extensions/extensions_test.go
- scripts/devbase.sh
- service.yaml
- stencil.lock
Promote rc to stable, created by `dt release promote`
**DO NOT MERGE**
> chore: Promote rc to stable

- docs/content/en/getting-started/module-quick-start.md
https://outreach-io.atlassian.net/browse/DT-3159
> chore: update module-quick-start.md with recent block changes

- .circleci/config.yml
- service.yaml
- stencil.lock
Switches to stable version of all module and re-stencils. Test of full release.
[XX-XX]
> fix: re-stencil 11-28-2022

- internal/codegen/tpl_stencil.go
* was setting it as a reflect.Value on accident. needs to be its
actual value
[XX-XX]
> fix: global value

- go.mod
- go.sum
- internal/modules/module_test.go
Title says, it does.
[DT-3248]
[DT-3248]: https://outreach-io.atlassian.net/browse/DT-3248?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(deps): update gobox to fix version resolution

- .gitignore
- cmd/stencil/stencil.go
- opslevel.yml
- service.yaml
- stencil.lock
restencil for [testing RC changes](https://outreach-io.atlassian.net/wiki/spaces/DT/pages/2388198102/SOP+Releasing+Dev+Tooling+Updates#Testing-RC-changes)
[XX-XX]
> fix: restencil for testing RC changes

- .circleci/config.yml
- opslevel.yml
- service.yaml
- stencil.lock
re-stencils to test release.
[XX-XX]
> fix: re-stencil

- .circleci/config.yml
- service.yaml
- stencil.lock
Skips e2e test since we don't have any, and skips docker since it will no longer work with the newest `devbase`.
[XX-XX]
> fix: skip e2e and docker steps

- .circleci/config.yml
- .github/dependabot.yml
- .vscode/private.env
- service.yaml
- stencil.lock
Alerts on build failures and cleans up some of the module dependencies so this project is more OSS frienly.
[DT-3401]
[DT-3401]: https://outreach-io.atlassian.net/browse/DT-3401?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: alert on build failure

- internal/codegen/tpl_stencil.go
* adds `stencil.Debug` function which proxies the arguments to
log.Debug (logrus)
[XX-XX]
> feat: debug log stencil function

- .circleci/config.yml
- .tool-versions
- .vscode/launch.json
- internal/codegen/tpl_stencil.go
- scripts/devbase.sh
- service.yaml
- stencil.lock
> fix: run stencil on stencil

- .circleci/config.yml
- .tool-versions
- go.mod
- go.sum
- service.yaml
- stencil.lock
> feat: tonymbugua-restencil

- .circleci/config.yml
- service.yaml
- stencil.lock
> feat(restencil): restencil

- .circleci/config.yml
- stencil.lock
> fix(stencil): Run stencil to remove Opslevel check

- docs/content/en/reference/native-extensions.md
Please read [CONTRIBUTING.md](CONTRIBUTING.md) for additional information on contributing to this repository!
Adress https://github.com/getoutreach/stencil/pull/303#discussion_r1432029206
[XX-XX]
> fix(docs): update wording

- .circleci/config.yml
- .goreleaser.yml
- .releaserc.yaml
- go.mod
- go.sum
- service.yaml
- stencil.lock
Please read [CONTRIBUTING.md](CONTRIBUTING.md) for additional information on contributing to this repository!
https://outreach-io.atlassian.net/browse/DT-4349
> fix(stencil): enable weekly RC release

- internal/modules/modules.go
- internal/modules/worklist.go
* data race on module resolution popped up in stencil-temporal tests
> fix: data race
